name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  KOMODO_URL: ${{ secrets.KOMODO_URL }}
  KOMODO_API_KEY: ${{ secrets.KOMODO_API_KEY }}
  KOMODO_API_SECRET: ${{ secrets.KOMODO_API_SECRET }}

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6.0.2

      - name: Test Deploy Stack Action
        id: test-deploy-stack
        uses: ./
        with:
          kind: stack
          patterns: '["dev_apps_website"]'

      - name: Test Run Procedure Action
        id: test-run-procedure
        uses: ./
        with:
          kind: procedure
          patterns: '["test-procedure"]'
      - name: Print Output
        id: output
        run:
          echo "${{ toJson(steps.test-deploy-stack.outputs.updates) }}" && echo
          "${{ toJson(steps.test-run-procedure.outputs.updates) }}"

      - name: Check summary file
        run: cat "$GITHUB_STEP_SUMMARY"
